name: documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install LaTeX packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-dateutil python3-sphinx latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 

      - name: Building the document
        run: |
          cd doc
          make html
