name: documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  sphinx-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ibressler/sphinx-action@master
        with:
          pre-build-command: "pip install numpy pandas && apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make html latexpdf"
          docs-folder: "doc"

      - name: Check for output
        run: ls -Rla doc/build/

      - name: Commit documentation changes to gh-pages branch
        run: |
          git clone https://github.com/BAMresearch/analyse_dls_with_contin.git --branch gh-pages --single-branch gh-pages
          cp -R doc/build/html/* gh-pages/
          cp doc/build/latex/analyse-dls-with-contin.pdf gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.

      - name: Push changes back to repo (gh-pages branch)
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
